### ISSUE TITLE
CAMValues Bug

### ISSUE THREAD

**Issue by p-hewson** [AndrewCMoore/Software-Security-Metrics-Calculator#35]
Error executing 'SSMC.commands.sampleCommand': java.lang.NullPointerException: Cannot invoke "ssmc.Method.getIdentifier()" because "m1" is null

Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException: Cannot invoke "ssmc.Method.getIdentifier()" because "m1" is null

line 140

**Comment by AndrewCMoore** [comment]
The issue was if the method and statement were on the same line in the compilation unit, the program would not identify the statement to be within the method. Thus by making the line number of the statement to be between or equals to the start/end line of the method.
